rw_root:
    pattern:  /
    defaults: { _controller: RwWebBundle:Default:redirect }

rw_welcome:
    pattern:  /welcome
    defaults: { _controller: RwWebBundle:Default:index }

rw_contact:
    pattern:  /contact
    defaults: { _controller: RwWebBundle:Default:contact }

rw_clean_time:
    pattern:  /register/clean_time_count
    defaults: { _controller: RwWebBundle:Default:cleanTimeCount }

rw_program:
    pattern:  /program
    defaults: { _controller: RwWebBundle:Program:index }

rw_register_convention_add:
    pattern:  /register/convention/__/add/{item}
    defaults: { _controller: RwWebBundle:Register:itemAdd }

rw_register_convention_clear:
    pattern:  /register/convention/__/clear
    defaults: { _controller: RwWebBundle:Register:itemClear }

rw_register_convention_verify_state:
    pattern:  /register/convention/__/verify/state
    defaults: { _controller: RwWebBundle:Register:verifyState }

rw_register_convention_checkout:
    pattern:  /register/convention/checkout
    defaults: { _controller: RwWebBundle:Register:itemCheckout }

rw_register_convention_checkout_success:
    pattern:  /register/convention/checkout/success
    defaults: { _controller: RwWebBundle:Register:itemCheckoutSuccess }

rw_register_convention:
    pattern:  /register/convention
    defaults: { _controller: RwWebBundle:Register:itemList }

rw_register_hotel:
    pattern:  /register/hotel
    defaults: { _controller: RwWebBundle:Register:hotel }

rw_about_committee:
    pattern:  /about/committee
    defaults: { _controller: RwWebBundle:About:committee }

rw_about_history:
    pattern:  /about/history
    defaults: { _controller: RwWebBundle:About:history }

rw_event:
    pattern:  /events
    defaults: { _controller: RwWebBundle:Event:index }