parameters:
    rf.listener.maintenance.class: Rw\WebBundle\Listener\Maintenance\MaintenanceListener
    rf.maintenance.controller.class: Rw\WebBundle\Controller\MaintenanceController
    rf.config.class: Rw\WebBundle\Utility\Config\YamlConfigContainer
    rf.config.twig.class: Rw\WebBundle\Templating\Extension\YamlConfigExtension
    rf.welcome.class: Rw\WebBundle\Utility\Welcome\WelcomeContainer
    rf.welcome.twig.class: Rw\WebBundle\Templating\Extension\WelcomeExtension
    scribe.parser.swim.class: Rw\WebBundle\Utility\Parser\Swim\SwimParser
    scribe.parser.swim.twig.class: Rw\WebBundle\Templating\Extension\SwimExtension
    rw.contact.type.class: Rw\WebBundle\Form\ContactType
    rw.checkout.type.class: Rw\WebBundle\Form\CheckoutType

services:
    rf.listener.maintenance:
        class:     "%rf.listener.maintenance.class%"
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: queryMaintenanceState }

    rf.maintenance.controller:
        class:     "%rf.maintenance.controller.class%"
        arguments: ["@service_container"]
        tags:
            - { name: maintenance.controller }

    rf.config:
        class:     "%rf.config.class%"
        arguments: ["@service_container"]
        tags:
            - { name: config.yml }

    rf.config.twig:
        class:     "%rf.config.twig.class%"
        arguments: ["@rf.config"]
        tags:
            - { name: twig.extension }

    rf.welcome:
        class:     "%rf.welcome.class%"
        arguments: ["@service_container"]
        tags:
            - { name: config.yml }

    rf.welcome.twig:
        class:     "%rf.welcome.twig.class%"
        arguments: ["@rf.welcome"]
        tags:
            - { name: twig.extension }

    scribe.parser.swim:
            class: %scribe.parser.swim.class%
            arguments: [ "@service_container" ]
            tags:
                - { name: parser.swim, alias: swim }

    scribe.parser.swim.twig:
        class:     "%scribe.parser.swim.twig.class%"
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    rw.contact.type:
        class:      %rw.contact.type.class%
        tags:
            - { name: form.type, alias: contact_type }

    rw.checkout.type:
        class:      %rw.checkout.type.class%
        tags:
            - { name: form.type, alias: checkout_type }