Rw\WebBundle\Entity\RegisterItemGroup:
    type: entity
    table: null
    repositoryClass: Rw\WebBundle\Entity\RegisterItemGroupRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        weight:
            type: integer
        emptyText:
            type: text
        showIfEmpty:
            type: boolean
    oneToMany:
        items:
            targetEntity: RegisterItem
            mappedBy: group
            orderBy: 
                weight: ASC
    lifecycleCallbacks: {  }
