Rw\WebBundle\Entity\Welcome:
    type: entity
    table: null
    repositoryClass: Rw\WebBundle\Entity\WelcomeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        header:
            type: string
            length: '100'
        body:
            type: text
        urlText:
            type: string
            length: '100'
            nullable: true
        urlHref:
            type: string
            length: '510'
            nullable: true
        matcher:
            type: string
            length: '255'
    lifecycleCallbacks: {  }