<?php

namespace Rw\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends EntityRepository
{
	public function getByContextOrderByWeight($context)
    {   
        $q = $this
            ->createQueryBuilder('c')
            ->where('c.context = :context')
            ->setParameter('context', $context)
            ->orderBy('c.weight', 'ASC')
            ->getQuery()
        ;
        
        try {
            $entries = $q->getResult();
        }
        catch (NoResultException $e) {
            return null;
        }

        return $entries;
    }

	public function getByContextOrderByPosition($context)
    {   
        $q = $this
            ->createQueryBuilder('c')
            ->where('c.context = :context')
            ->setParameter('context', $context)
            ->orderBy('c.position', 'ASC')
            ->getQuery()
        ;
        
        try {
            $entries = $q->getResult();
        }
        catch (NoResultException $e) {
            return null;
        }

        return $entries;
    }
}
