<?php

namespace Rw\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterPurchaseRepository extends EntityRepository
{
}
